export const APP_STORE_URL =
  "https://apps.apple.com/us/app/filmsera-group-film-camera/id6781880091";
export const APP_ID = "6781880091";
export const SITE_URL = "https://getfilmsera.cam";

export type Camera = {
  id: string;
  slug: string;
  name: string;
  blurb: string;
  story: string;
  section: string;
  isPremium: boolean;
  modelNumber: string;
  stockCode: string;
  icon: string;
  cover: string;
  strip: string[];
};

/** Full Cameras catalog — graded SampleStrip exports from the iOS app. */
export const CAMERAS: Camera[] = [
  {
    id: "dzfilm",
    slug: "dzfilm",
    name: "DZ Film",
    blurb: "Clean modern film. The everyday look.",
    story: "The everyday stock. Balanced color, honest grain — the roll you'd keep loaded for whatever the day brings.",
    section: "Originals",
    isPremium: false,
    modelNumber: "5677",
    stockCode: "ISO 400",
    icon: "/shots/cameras/dzfilm/icon.png",
    cover: "/shots/cameras/dzfilm/s2.jpg",
    strip: ["/shots/cameras/dzfilm/s0.jpg", "/shots/cameras/dzfilm/s1.jpg", "/shots/cameras/dzfilm/s2.jpg"],
  },
  {
    id: "disposable",
    slug: "disposable",
    name: "Disposable",
    blurb: "Harsh flash, warm grain, 27 shots.",
    story: "A plastic one-shot from the gas-station counter. 27 frames, a harsh little flash, and no second chances.",
    section: "Originals",
    isPremium: false,
    modelNumber: "1043",
    stockCode: "ISO 800",
    icon: "/shots/cameras/disposable/icon.png",
    cover: "/shots/cameras/disposable/s2.jpg",
    strip: ["/shots/cameras/disposable/s0.jpg", "/shots/cameras/disposable/s1.jpg", "/shots/cameras/disposable/s2.jpg"],
  },
  {
    id: "instant",
    slug: "instant",
    name: "Instant",
    blurb: "Wide white border. Watch it develop.",
    story: "Press the button, pull the print, shake it into existence. The party camera that made every fridge a gallery.",
    section: "Originals",
    isPremium: false,
    modelNumber: "3746",
    stockCode: "SX-70",
    icon: "/shots/cameras/instant/icon.png",
    cover: "/shots/cameras/instant/s2.jpg",
    strip: ["/shots/cameras/instant/s0.jpg", "/shots/cameras/instant/s1.jpg", "/shots/cameras/instant/s2.jpg"],
  },
  {
    id: "vhs",
    slug: "vhs",
    name: "VHS",
    blurb: "Scan lines, timecode, tracking noise.",
    story: "Top-loading tape-deck energy. Tracking noise, timecode, and the soft hum of a Friday night recording.",
    section: "Originals",
    isPremium: false,
    modelNumber: "7696",
    stockCode: "SP 120MIN",
    icon: "/shots/cameras/vhs/icon.png",
    cover: "/shots/cameras/vhs/s2.jpg",
    strip: ["/shots/cameras/vhs/s0.jpg", "/shots/cameras/vhs/s1.jpg", "/shots/cameras/vhs/s2.jpg"],
  },
  {
    id: "eightmm",
    slug: "eightmm",
    name: "8mm",
    blurb: "Sprockets, gate weave, heavy warm grain.",
    story: "Home movies from a sunlit decade. Sprockets, gate weave, and grain you can almost hear clicking through the projector.",
    section: "Originals",
    isPremium: false,
    modelNumber: "5566",
    stockCode: "SP 120MIN",
    icon: "/shots/cameras/eightmm/icon.png",
    cover: "/shots/cameras/eightmm/s2.jpg",
    strip: ["/shots/cameras/eightmm/s0.jpg", "/shots/cameras/eightmm/s1.jpg", "/shots/cameras/eightmm/s2.jpg"],
  },
  {
    id: "digi",
    slug: "digicam",
    name: "Digicam",
    blurb: "Early-2000s digicam. Crunchy and bright.",
    story: "An early-2000s pocket digicam. Crunchy sharpening, brave colors, four megapixels of pure confidence.",
    section: "Originals",
    isPremium: true,
    modelNumber: "9702",
    stockCode: "3.2 MPX",
    icon: "/shots/cameras/digi/icon.png",
    cover: "/shots/cameras/digi/s2.jpg",
    strip: ["/shots/cameras/digi/s0.jpg", "/shots/cameras/digi/s1.jpg", "/shots/cameras/digi/s2.jpg"],
  },
  {
    id: "note",
    slug: "note",
    name: "Notebook",
    blurb: "Signs each frame with a handwritten date.",
    story: "The keepsake camera. A clean, warm everyday stock that signs every frame in ink — the date scrawled in the corner like a line from a diary.",
    section: "Originals",
    isPremium: true,
    modelNumber: "7021",
    stockCode: "ISO 400",
    icon: "/shots/cameras/note/icon.png",
    cover: "/shots/cameras/note/s2.jpg",
    strip: ["/shots/cameras/note/s0.jpg", "/shots/cameras/note/s1.jpg", "/shots/cameras/note/s2.jpg"],
  },
  {
    id: "oldiphone",
    slug: "oldiphone",
    name: "Pocket Cam",
    blurb: "First-gen smartphone nostalgia.",
    story: "The phone camera that started the feed era. Soft, small, and accidentally nostalgic.",
    section: "Originals",
    isPremium: true,
    modelNumber: "5023",
    stockCode: "3.2 MPX",
    icon: "/shots/cameras/oldiphone/icon.png",
    cover: "/shots/cameras/oldiphone/s2.jpg",
    strip: ["/shots/cameras/oldiphone/s0.jpg", "/shots/cameras/oldiphone/s1.jpg", "/shots/cameras/oldiphone/s2.jpg"],
  },
  {
    id: "slide",
    slug: "slide",
    name: "Slide",
    blurb: "Cardboard mount, saturated Velvia color.",
    story: "Reversal film in a cardboard mount, saturated like a projector beam in a dark living room.",
    section: "Originals",
    isPremium: true,
    modelNumber: "6342",
    stockCode: "ISO 400",
    icon: "/shots/cameras/slide/icon.png",
    cover: "/shots/cameras/slide/s2.jpg",
    strip: ["/shots/cameras/slide/s0.jpg", "/shots/cameras/slide/s1.jpg", "/shots/cameras/slide/s2.jpg"],
  },
  {
    id: "cpm35",
    slug: "sprocket",
    name: "Sprocket 35",
    blurb: "Classic 35mm with sprockets and frame numbers.",
    story: "A classic 35mm compact. Frame numbers on the rebate, an amber date in the corner, light leaks included free of charge.",
    section: "Originals",
    isPremium: true,
    modelNumber: "4761",
    stockCode: "ISO 400",
    icon: "/shots/cameras/cpm35/icon.png",
    cover: "/shots/cameras/cpm35/s2.jpg",
    strip: ["/shots/cameras/cpm35/s0.jpg", "/shots/cameras/cpm35/s1.jpg", "/shots/cameras/cpm35/s2.jpg"],
  },
  {
    id: "glow",
    slug: "glow",
    name: "Glow",
    blurb: "Dreamy halation bloom around the highlights.",
    story: "Halation like a memory. Highlights bloom, blacks lift, and everything looks like it happened years ago.",
    section: "Originals",
    isPremium: true,
    modelNumber: "2140",
    stockCode: "ISO 400",
    icon: "/shots/cameras/glow/icon.png",
    cover: "/shots/cameras/glow/s2.jpg",
    strip: ["/shots/cameras/glow/s0.jpg", "/shots/cameras/glow/s1.jpg", "/shots/cameras/glow/s2.jpg"],
  },
  {
    id: "d3d",
    slug: "d3d",
    name: "Anaglyph",
    blurb: "Anaglyph 3D. Grab the red/blue glasses.",
    story: "A red-and-blue anaglyph oddity. Find the cardboard glasses in a drawer and watch the picture pop.",
    section: "Originals",
    isPremium: true,
    modelNumber: "1060",
    stockCode: "3.2 MPX",
    icon: "/shots/cameras/d3d/icon.png",
    cover: "/shots/cameras/d3d/s2.jpg",
    strip: ["/shots/cameras/d3d/s0.jpg", "/shots/cameras/d3d/s1.jpg", "/shots/cameras/d3d/s2.jpg"],
  },
  {
    id: "instasqc",
    slug: "instasqc",
    name: "Pastel Square",
    blurb: "Square instant. Soft, pastel, framed.",
    story: "The square instant. Pastel chemistry, a white border, and a caption line waiting at the bottom.",
    section: "Originals",
    isPremium: true,
    modelNumber: "3145",
    stockCode: "SX-70",
    icon: "/shots/cameras/instasqc/icon.png",
    cover: "/shots/cameras/instasqc/s2.jpg",
    strip: ["/shots/cameras/instasqc/s0.jpg", "/shots/cameras/instasqc/s1.jpg", "/shots/cameras/instasqc/s2.jpg"],
  },
  {
    id: "sixteenmm",
    slug: "sixteenmm",
    name: "16mm",
    blurb: "Newsreel stock. Narrow sprockets, serious grain.",
    story: "Newsreel stock. Narrow dual sprockets, a touch of gate weave, and grain that means business.",
    section: "Film Pack 01",
    isPremium: true,
    modelNumber: "6037",
    stockCode: "SP 120MIN",
    icon: "/shots/cameras/sixteenmm/icon.png",
    cover: "/shots/cameras/sixteenmm/s2.jpg",
    strip: ["/shots/cameras/sixteenmm/s0.jpg", "/shots/cameras/sixteenmm/s1.jpg", "/shots/cameras/sixteenmm/s2.jpg"],
  },
  {
    id: "dcr",
    slug: "camcorder",
    name: "Camcorder",
    blurb: "Camcorder scan lines and green timecode.",
    story: "A shoulder-strap camcorder with a flip-out screen. Scan lines, green timecode, birthday-party autofocus.",
    section: "Film Pack 01",
    isPremium: true,
    modelNumber: "9206",
    stockCode: "SP 120MIN",
    icon: "/shots/cameras/dcr/icon.png",
    cover: "/shots/cameras/dcr/s2.jpg",
    strip: ["/shots/cameras/dcr/s0.jpg", "/shots/cameras/dcr/s1.jpg", "/shots/cameras/dcr/s2.jpg"],
  },
  {
    id: "kino",
    slug: "kino",
    name: "Kino",
    blurb: "Anamorphic bars. Warm, quiet contrast.",
    story: "Wide-screen romance. Anamorphic bars, warm halation, and contrast that whispers instead of shouts.",
    section: "Film Pack 01",
    isPremium: true,
    modelNumber: "1182",
    stockCode: "ISO 400",
    icon: "/shots/cameras/kino/icon.png",
    cover: "/shots/cameras/kino/s2.jpg",
    strip: ["/shots/cameras/kino/s0.jpg", "/shots/cameras/kino/s1.jpg", "/shots/cameras/kino/s2.jpg"],
  },
  {
    id: "s67",
    slug: "s67",
    name: "Heirloom",
    blurb: "Medium format. Creamy, calm, unhurried.",
    story: "Medium-format manners. A big, calm negative — creamy tones, gentle drama, absolutely no hurry.",
    section: "Film Pack 02",
    isPremium: true,
    modelNumber: "4953",
    stockCode: "ISO 400",
    icon: "/shots/cameras/s67/icon.png",
    cover: "/shots/cameras/s67/s2.jpg",
    strip: ["/shots/cameras/s67/s0.jpg", "/shots/cameras/s67/s1.jpg", "/shots/cameras/s67/s2.jpg"],
  },
  {
    id: "grf",
    slug: "grf",
    name: "Noir",
    blurb: "Street B&W. Deep blacks, no mercy.",
    story: "A black pocket brick beloved by street shooters. Contrasty black-and-white, deep shadows, zone-focus speed.",
    section: "Film Pack 02",
    isPremium: true,
    modelNumber: "2438",
    stockCode: "ISO 400",
    icon: "/shots/cameras/grf/icon.png",
    cover: "/shots/cameras/grf/s2.jpg",
    strip: ["/shots/cameras/grf/s0.jpg", "/shots/cameras/grf/s1.jpg", "/shots/cameras/grf/s2.jpg"],
  },
  {
    id: "original",
    slug: "original",
    name: "Original",
    blurb: "The drugstore standard. Golden and soft.",
    story: "The drugstore standard. Golden warmth and soft contrast — the look every shoebox of prints shares.",
    section: "Film Pack 02",
    isPremium: true,
    modelNumber: "5290",
    stockCode: "ISO 400",
    icon: "/shots/cameras/original/icon.png",
    cover: "/shots/cameras/original/s2.jpg",
    strip: ["/shots/cameras/original/s0.jpg", "/shots/cameras/original/s1.jpg", "/shots/cameras/original/s2.jpg"],
  },
  {
    id: "college",
    slug: "college",
    name: "Yearbook",
    blurb: "Yearbook flash. Bright, green, unflinching.",
    story: "Yearbook night. Direct flash, slightly green fluorescents, and everyone's eyes a little red.",
    section: "Film Pack 02",
    isPremium: true,
    modelNumber: "4018",
    stockCode: "ISO 800",
    icon: "/shots/cameras/college/icon.png",
    cover: "/shots/cameras/college/s2.jpg",
    strip: ["/shots/cameras/college/s0.jpg", "/shots/cameras/college/s1.jpg", "/shots/cameras/college/s2.jpg"],
  },
  {
    id: "noga",
    slug: "noga",
    name: "Light Leak",
    blurb: "Eastern-bloc box. Wild leaks, zero apologies.",
    story: "A brassy Eastern-bloc box with a mind of its own. Heavy vignette, wild leaks, zero apologies.",
    section: "Film Pack 03",
    isPremium: true,
    modelNumber: "1930",
    stockCode: "ISO 400",
    icon: "/shots/cameras/noga/icon.png",
    cover: "/shots/cameras/noga/s2.jpg",
    strip: ["/shots/cameras/noga/s0.jpg", "/shots/cameras/noga/s1.jpg", "/shots/cameras/noga/s2.jpg"],
  },
  {
    id: "gulf",
    slug: "gulf",
    name: "Sunbleached",
    blurb: "Sun-bleached '70s. Yellowed and faded.",
    story: "Sun-bleached like a photo left on a dashboard since 1976. Yellowed highlights, faded blacks, warm dust.",
    section: "Film Pack 03",
    isPremium: true,
    modelNumber: "3051",
    stockCode: "ISO 400",
    icon: "/shots/cameras/gulf/icon.png",
    cover: "/shots/cameras/gulf/s2.jpg",
    strip: ["/shots/cameras/gulf/s0.jpg", "/shots/cameras/gulf/s1.jpg", "/shots/cameras/gulf/s2.jpg"],
  },
  {
    id: "vfone",
    slug: "vfone",
    name: "Keychain",
    blurb: "A lens the size of a lentil.",
    story: "A flip-phone lens the size of a lentil. Low saturation, mushy detail, undeniable charm.",
    section: "Film Pack 03",
    isPremium: true,
    modelNumber: "9687",
    stockCode: "3.2 MPX",
    icon: "/shots/cameras/vfone/icon.png",
    cover: "/shots/cameras/vfone/s2.jpg",
    strip: ["/shots/cameras/vfone/s0.jpg", "/shots/cameras/vfone/s1.jpg", "/shots/cameras/vfone/s2.jpg"],
  },
  {
    id: "tam",
    slug: "tam",
    name: "Toy Cam",
    blurb: "Plastic toy cam. Tunnel vignette, loud color.",
    story: "A plastic toy camera that takes itself completely seriously. Oversaturated, tunnel vignette, focus optional.",
    section: "Film Pack 03",
    isPremium: true,
    modelNumber: "2249",
    stockCode: "ISO 800",
    icon: "/shots/cameras/tam/icon.png",
    cover: "/shots/cameras/tam/s2.jpg",
    strip: ["/shots/cameras/tam/s0.jpg", "/shots/cameras/tam/s1.jpg", "/shots/cameras/tam/s2.jpg"],
  },
  {
    id: "ne135",
    slug: "ne135",
    name: "Midnight",
    blurb: "Night-edition cine. Cool and blue-shadowed.",
    story: "Night-edition cine stock. Cool neutrals, gentle contrast, shadows that stay a little blue.",
    section: "Film Pack 03",
    isPremium: true,
    modelNumber: "7731",
    stockCode: "ISO 400",
    icon: "/shots/cameras/ne135/icon.png",
    cover: "/shots/cameras/ne135/s2.jpg",
    strip: ["/shots/cameras/ne135/s0.jpg", "/shots/cameras/ne135/s1.jpg", "/shots/cameras/ne135/s2.jpg"],
  },
] as const;

/** Shelf highlight — free originals + popular packs for homepage carousel. */
export const LOOKS = CAMERAS.filter((c) =>
  ["disposable", "vhs", "eightmm", "instant", "digi", "glow", "dcr", "cpm35", "sixteenmm", "kino", "dzfilm", "original"].includes(c.id)
);

export const FILM_STRIP = CAMERAS.flatMap((c) => c.strip).slice(0, 18);

export const HOW_STEPS = [
  { n: "1", title: "Create a Film", body: "Name it, pick a Look, set when it develops.", screen: "/shots/screens/01-start.png" },
  { n: "2", title: "Guests join", body: "Share a QR or link. Guests open Filmsera.", screen: "/shots/screens/06-group.png" },
  { n: "3", title: "Shoot Shots", body: "Every Frame drops into the roll — unseen.", screen: "/shots/screens/03-capture.png" },
  { n: "4", title: "Reveal", body: "The timer hits zero. The album opens together.", screen: "/shots/screens/05-reveal.png" },
] as const;
